name: Deploy

on:
  push:
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'
      - '**.json'
  workflow_dispatch:

jobs:
  build:
    name: Build and deploy 
    runs-on: ubuntu-latest
    steps:
    - name: ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          cd ${{ secrets.NAME }}
          git clone https://${{ secrets.GITHUB }}@github.com/Nes0x/${{ secrets.NAME }}.git || (cd ${{ secrets.NAME }} ; git fetch --all ; git reset --hard origin/master)
          cd ${{ secrets.NAME }}
          screen -X -S "${{ secrets.NAME }}" quit
          ${{ secrets.DOTNET }} build --configuration Release
          cd ${{ secrets.PATH }}
          nohup screen -d -m -S ${{ secrets.NAME }} ${{ secrets.DOTNET }} ${{ secrets.NAME }}.dll ${{ secrets.TOKEN }}
